spring:
  application:
    name: account # 服务名称
nacos:
  config:
    server-addr: 192.168.1.122:8848 # Nacos地址
    username: nacos
    password: 123456
    namespace: dev
    bootstrap:
      enable: true
    auto-refresh: true
    config-long-poll-timeout: 46000
    config-retry-time: 2333
    data-id: account.yaml
    group: DEFAULT_GROUP
    max-retry: 10
    type: yaml
    ext-config:
      - data-id: common.yaml
        type: yaml
        enable-remote-sync-config: true